import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Built tracker IIFE shipped as a static asset.
    "public/**",
    // Auto-generated by `payload migrate:create`.
    "src/migrations/**",
  ]),
]);

export default eslintConfig;
